# This file makes the 'stratagem_creators' directory a Python package.

from .undercut_stratagem_creator import try_create as try_create_undercut_stratagem
from .coordinate_pricing_stratagem_creator import try_create as try_create_coordinate_pricing_stratagem
from .hoard_resource_stratagem_creator import try_create as try_create_hoard_resource_stratagem
from .political_campaign_stratagem_creator import try_create as try_create_political_campaign_stratagem
from .reputation_assault_stratagem_creator import try_create as try_create_reputation_assault_stratagem
from .emergency_liquidation_stratagem_creator import try_create as try_create_emergency_liquidation_stratagem
from .cultural_patronage_stratagem_creator import try_create as try_create_cultural_patronage_stratagem
from .information_network_stratagem_creator import try_create as try_create_information_network_stratagem
from .maritime_blockade_stratagem_creator import try_create as try_create_maritime_blockade_stratagem
from .theater_conspiracy_stratagem_creator import try_create as try_create_theater_conspiracy_stratagem
from .printing_propaganda_stratagem_creator import try_create as try_create_printing_propaganda_stratagem
from .cargo_mishap_stratagem_creator import try_create as try_create_cargo_mishap_stratagem
from .marketplace_gossip_stratagem_creator import try_create as try_create_marketplace_gossip_stratagem
from .employee_poaching_stratagem_creator import try_create as try_create_employee_poaching_stratagem
from .joint_venture_stratagem_creator import try_create as try_create_joint_venture_stratagem
# Placeholder for monopoly_pricing
# from .monopoly_pricing_stratagem_creator import try_create as try_create_monopoly_pricing_stratagem
# Placeholder for reputation_boost
# from .reputation_boost_stratagem_creator import try_create as try_create_reputation_boost_stratagem
# Placeholder for canal_mugging
# from .canal_mugging_stratagem_creator import try_create as try_create_canal_mugging_stratagem
# Placeholder for burglary
# from .burglary_stratagem_creator import try_create as try_create_burglary_stratagem
# Placeholder for employee_corruption
# from .employee_corruption_stratagem_creator import try_create as try_create_employee_corruption_stratagem
# Import other stratagem creators here as they are developed
